version: "3.5"

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
      - "9090:9000"
    networks:
      - backend
  redis: 
    container_name: redis
    image: 'redis:5.0.7-alpine'
    ports:
      - 6379:6379
    networks:
      - backend
networks:
    backend:
      name: backend